// <auto-generated />
using System;
using EntityFrameWorkRelationships.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFrameWorkRelationships.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20201023145223_OneToOneMigration")]
    partial class OneToOneMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityFrameWorkRelationships.Models.Adresse", b =>
                {
                    b.Property<int>("AdresseId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnName("CodePostal")
                        .HasColumnType("nvarchar")
                        .HasMaxLength(8);

                    b.Property<int>("NumeroCivique")
                        .HasColumnName("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasColumnName("Rue")
                        .HasColumnType("nvarchar")
                        .HasMaxLength(200);

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnName("Ville")
                        .HasColumnType("nvarchar")
                        .HasMaxLength(100);

                    b.HasKey("AdresseId");

                    b.ToTable("Adresse");
                });

            modelBuilder.Entity("EntityFrameWorkRelationships.Models.Personne", b =>
                {
                    b.Property<int>("PersonneId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdresseId");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnName("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnName("Nom")
                        .HasColumnType("nvarchar")
                        .HasMaxLength(120);

                    b.Property<decimal?>("Poids")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 38, scale: 17)))
                        .HasColumnName("Poids")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("PersonneId");

                    b.HasIndex("AdresseId")
                        .IsUnique()
                        .HasFilter("[AdresseId] IS NOT NULL");

                    b.ToTable("Personne");
                });

            modelBuilder.Entity("EntityFrameWorkRelationships.Models.Personne", b =>
                {
                    b.HasOne("EntityFrameWorkRelationships.Models.Adresse", "Adresse")
                        .WithOne("Personne")
                        .HasForeignKey("EntityFrameWorkRelationships.Models.Personne", "AdresseId");
                });
#pragma warning restore 612, 618
        }
    }
}
