// <auto-generated />
using System;
using EntityFrameWorkRelationships.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFrameWorkRelationships.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20201027021031_ManyToManyMigration")]
    partial class ManyToManyMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityFrameWorkRelationships.Models.Adresse", b =>
                {
                    b.Property<int>("AdresseId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnName("CodePostal")
                        .HasColumnType("text")
                        .HasMaxLength(8);

                    b.Property<int>("NumeroCivique")
                        .HasColumnName("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasColumnName("Rue")
                        .HasColumnType("text")
                        .HasMaxLength(200);

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnName("Ville")
                        .HasColumnType("text")
                        .HasMaxLength(100);

                    b.HasKey("AdresseId");

                    b.ToTable("Adresse");
                });

            modelBuilder.Entity("EntityFrameWorkRelationships.Models.Personne", b =>
                {
                    b.Property<int>("PersonneId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdresseId");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnName("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnName("Nom")
                        .HasColumnType("text")
                        .HasMaxLength(120);

                    b.Property<decimal?>("Poids")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 38, scale: 17)))
                        .HasColumnName("Poids")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("TelephoneId");

                    b.HasKey("PersonneId");

                    b.HasIndex("AdresseId");

                    b.HasIndex("TelephoneId")
                        .IsUnique()
                        .HasFilter("[TelephoneId] IS NOT NULL");

                    b.ToTable("Personne");
                });

            modelBuilder.Entity("EntityFrameWorkRelationships.Models.PersonneProfession", b =>
                {
                    b.Property<int>("PersonneId");

                    b.Property<int>("ProfessionId");

                    b.Property<decimal?>("Salaire")
                        .HasColumnName("Salaire")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("PersonneId", "ProfessionId");

                    b.HasIndex("ProfessionId");

                    b.ToTable("PersonneProfession");
                });

            modelBuilder.Entity("EntityFrameWorkRelationships.Models.Profession", b =>
                {
                    b.Property<int>("ProfessionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title");

                    b.HasKey("ProfessionId");

                    b.ToTable("Profession");
                });

            modelBuilder.Entity("EntityFrameWorkRelationships.Models.Telephone", b =>
                {
                    b.Property<int>("TelephoneId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnName("Numero")
                        .HasColumnType("text")
                        .HasMaxLength(10);

                    b.HasKey("TelephoneId");

                    b.ToTable("Telephone");
                });

            modelBuilder.Entity("EntityFrameWorkRelationships.Models.Personne", b =>
                {
                    b.HasOne("EntityFrameWorkRelationships.Models.Adresse", "Adresse")
                        .WithMany("Personnes")
                        .HasForeignKey("AdresseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EntityFrameWorkRelationships.Models.Telephone", "Telephone")
                        .WithOne("Personne")
                        .HasForeignKey("EntityFrameWorkRelationships.Models.Personne", "TelephoneId");
                });

            modelBuilder.Entity("EntityFrameWorkRelationships.Models.PersonneProfession", b =>
                {
                    b.HasOne("EntityFrameWorkRelationships.Models.Personne", "Personne")
                        .WithMany("PersonneProfessions")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EntityFrameWorkRelationships.Models.Profession", "Profession")
                        .WithMany("PersonneProfessions")
                        .HasForeignKey("ProfessionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
